### ISSUE TITLE
Camera-Ready Submission

### ISSUE THREAD

**Issue by Nidchakan** [Nidchakan/PhayaoTown#14]

**Comment by ADissT** [comment]
Word : https://www.dropbox.com/home/PhayaoTown/AUCC_2019?preview=AUCC2019-sid77-Camera-Ready-Oral.docx

**Comment by ADissT** [comment]
PDF : https://www.dropbox.com/home/PhayaoTown/AUCC2019?preview=AUCC2019-sid77-Camera-Ready-Oral.pdf

**Comment by Nidchakan** [comment]
@ajkiattikul 
![payment](https://user-images.githubusercontent.com/48169744/53691692-e9a83280-3db5-11e9-9b9d-d1e7f1f4dde1.png)
![submission1](https://user-images.githubusercontent.com/48169744/53691701-1f4d1b80-3db6-11e9-8dc6-1805ecd4a056.png)
![submission2](https://user-images.githubusercontent.com/48169744/53691706-37249f80-3db6-11e9-9976-4880648377b6.png)

**Comment by ajkiattikul** [comment]
@Nidchakan  ถ้าครบ 24 ชมแล้ว ลองตรวจสอบอีกทีว่า payment เขาแจ้งว่าอย่างไร
น่าจะครบละนะ เราอัพโหลดวันอาทิตย์นิ

**Comment by Nidchakan** [comment]
![image](https://user-images.githubusercontent.com/48169744/53804756-e8743280-3f7a-11e9-8c26-f8c5c941b694.png)
