### ISSUE TITLE
Phayao town บทที่ 1-2-3 

### ISSUE THREAD

**Issue by ADissT** [Nidchakan/PhayaoTown#32]

**Comment by ADissT** [comment]
[รวมบทที่ 1-2-3.docx](https://github.com/Nidchakan/PhayaoTown/files/3115148/1-2-3.docx)

**Comment by ADissT** [comment]
PDF : 
[รวมบทที่ 1-2-3.pdf](https://github.com/Nidchakan/PhayaoTown/files/3115154/1-2-3.pdf)

**Comment by ADissT** [comment]
PDF บทที่ 1 , 2 , 3
[รวมบทที่ 1-2-3.pdf](https://github.com/Nidchakan/PhayaoTown/files/3115627/1-2-3.pdf)

**Comment by ADissT** [comment]
Update 18:15 น.
ปรับปรุงแบบฟอร์มรูปเล่ม
[**Download Docx**](https://www.dropbox.com/s/96b1acgutjc09aj/190425_%E0%B8%9A%E0%B8%97%E0%B8%97%E0%B8%B5%E0%B9%881.docx?dl=0)
[**Download PDF**](https://www.dropbox.com/s/stoaovgnqjnndnf/190425_%E0%B8%9A%E0%B8%97%E0%B8%97%E0%B8%B5%E0%B9%881.pdf?dl=0)

**Comment by ajkiattikul** [comment]
[1-2-3.pdf](https://github.com/Nidchakan/PhayaoTown/files/3119803/1-2-3.pdf)
มีแก้นิดหน่อย

**Comment by ADissT** [comment]
[**Download**](https://www.dropbox.com/s/i0srlr0e7eoxqti/190429_%E0%B8%9A%E0%B8%97%E0%B8%97%E0%B8%B5%E0%B9%881.docx?dl=0)

**Comment by ADissT** [comment]
[190429_บทที่1.docx](https://github.com/Nidchakan/PhayaoTown/files/3126421/190429_.1.docx)
